### ISSUE TITLE
Add a “Clear” or “Start new analysis” button

### ISSUE THREAD

**Issue by shashwatsahay** [sebastiantiesmeyer/ssamLite#16]

**Comment by sebastiantiesmeyer** [comment]
I think it should be fine if ppl just reload the page (this is the way I would implement such a button as well onclick->document.reload() : )
And another button would just take up real estate...

**Comment by niklasmueboe** [comment]
To be honest, I disagree, users might get stuck there. And if the implementation is that easy why not do it

**Comment by shashwatsahay** [comment]
Maybe I can add this button next to the data centre or it can appear in the header after data is loaded....
let me try this and see how it looks

**Comment by sebastiantiesmeyer** [comment]
Ok, I put sth together : )

**Comment by sebastiantiesmeyer** [comment]
Oh sry, I didn't see that you re-assigned the task

**Comment by shashwatsahay** [comment]
@sebastiantiesmeyer  Can you please state the commit which fixed this....

**Comment by sebastiantiesmeyer** [comment]
https://github.com/sebastiantiesmeyer/ssamLite/commit/b56bc47fffc1df2cbb6c19df3777a4b949bf02ab
tyg

**Comment by shashwatsahay** [comment]
thanks
